### ISSUE TITLE
Burrito failed to wrap up your app

### ISSUE THREAD

**Issue by mxgrn** [mhanberg/lazyasdf#13]
Trying to install via Homebrew, currently getting this error:

```
Last 15 lines from /Users/mxgrn/Library/Logs/Homebrew/lazyasdf/05.mix:
--> PHASE: :build
---> Generating wrapper metadata file...
error(link): undefined reference to symbol 'dyld_stub_binder'
error: UndefinedSymbolReference
---> Cleaning up...
---> Burrito failed to wrap up your app! Check the logs for more information.
** (RuntimeError) Wrapper build failed
    (burrito 0.8.0) lib/steps/build/pack_and_build.ex:54: Burrito.Steps.Build.PackAndBuild.execute/1
    (burrito 0.8.0) lib/builder/builder.ex:146: anonymous fn/3 in Burrito.Builder.run_phase/2
    (elixir 1.15.7) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.15.7) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
    (burrito 0.8.0) lib/builder/builder.ex:95: Burrito.Builder.build/1
    (mix 1.15.7) lib/mix/tasks/release.ex:1064: Mix.Tasks.Release.run_steps/1
    (mix 1.15.7) lib/mix/task.ex:455: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.7) lib/mix/cli.ex:92: Mix.CLI.run_task/2
```

**Comment by mhanberg** [comment]
Need to bump burrito and zig versions. Are you on macOS 14?

**Comment by mxgrn** [comment]
Yep
