### ISSUE TITLE
Error trying to start it up

### ISSUE THREAD

**Issue by gastonrey** [mhanberg/lazyasdf#5]
Hi, I'm trying this out, just installed and when trying to start it up I get this error:

```
15:02:58.888 [error] Error in application loop:
  ** (MatchError) no match of right hand side value: {"No plugins installed\n", 1}
    (lazyasdf 0.1.0) lib/lazyasdf/asdf.ex:53: Lazyasdf.Asdf.asdf/1
    (lazyasdf 0.1.0) lib/lazyasdf/asdf.ex:33: Lazyasdf.Asdf.plugin_list/0
    (lazyasdf 0.1.0) lib/lazyasdf/pane/plugins.ex:16: Lazyasdf.Pane.Plugins.init/0
    (lazyasdf 0.1.0) lib/lazyasdf/app.ex:24: Lazyasdf.App.init/1
    (ratatouille 0.5.1) lib/ratatouille/runtime.ex:155: Ratatouille.Runtime.initial_model/1
    (ratatouille 0.5.1) lib/ratatouille/runtime.ex:100: Ratatouille.Runtime.run/1
    (elixir 1.14.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3


15:02:58.890 [warning] The Ratatouille termbox window was automatically closed due to an error (you may need to quit Erlang manually).
```

MacOS: Ventura 13.2
Hardware: M1
asdf: installed
Elixir/OTP: Installed
Shell: ZSH
Command I run to start: lazyasdf

**Comment by mhanberg** [comment]
Hi!

This is a combo issue of lazyasdf doesn't do any error handling yet, as well as you don't have any asdf plugins installed. 

lazyasdf doesn't allow you to install plugins yet, so you wouldn't be able to do anything anyway.

**Comment by gastonrey** [comment]
Thanks for your reply, thought it was aimed to install plugins :)

**Comment by mhanberg** [comment]
In a future release, maybe!

**Comment by nielsbom** [comment]
In #4 it was discovered that resizing the window hides the error. Not sure how functional lazyasdf is tho.
